### PR TITLE
Adds travis ci integration 

### LINKED ISSUE #150: Add Travis integetion
- [x] use `npm:test` (aka gulp lint) on PR/PR-commit

### PR DESCRIPTION
**Pull request by nickwynja**
Close #150

### CODE REVIEW

**Comment by nickwynja** [comment]
@clepore I have it `npm install` and then just run `gulp`, which does the linting but also builds the package... so if there's anything in it that passes lint but still actually breaks the build, it'll let us know.

**Comment by clepore** [comment]
I saw that - it makes sense to me.

**Comment by clepore** [comment]
@nickwynja Should this be merged in?

**Comment by nickwynja** [comment]
@clepore I've been holding it since we don't have a none-release branch. If you want to create a `develop` branch off of `1.x` then we could merge this into `develop`.

**Pull request merged**
