### PR TITLE
200 - Support themes

### LINKED ISSUE #200: Support uplift dark and contrast themes
**Is your feature request related to a problem? Please describe.**
Once we've added the theme variants to `ids-identity`, add the proper stylesheets to generate the new theme variants.

**Describe the solution you'd like**
Depends on https://github.com/infor-design/design-system/issues/299

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by jmacaluso711**
**Explain the _details_ for making this change. What existing problem does the pull request solve?**
Adds theme switching to the css site and fab (theme switcher) package. The fab deviates slightly from the design. The buttons are aligned in a vertical row to support more use cases.

**Related github/jira issue (required)**:
closes #200 

**Steps necessary to review your pull request (required)**:
- Pull branch & run `npm start`
- got to http://localhost:3000
- theme switcher is in the bottom right corner

### CODE REVIEW

**Comment by jmacaluso711** [comment]
@nickwynja  that seems to be coming from the tokens for dark and contrast. `--theme-font-family-base: helvetica, arial, sans-serif;` and `--theme-size-font-base: 1.4rem;`

**Comment by clepore** [comment]
slack-imgs

So per our slack discussion,
- [ ] Shift all soho themes over to uplift themes
- [ ] Add an active state (doesn't have to be persistent) to the theme `fab`

**Comment by nickwynja** [comment]
I think this is fine to merge. The themes expose some errors in, what I'd guess at least, the tokens. See the buttons demo and switch themes to see issues with the button label colors.

@jmacaluso711 Can you confirm whether it's the token definition that's incorrect or whether we're simply not using the token in those cases?

**Comment by jmacaluso711** [comment]
It appears we are using the wrong token on `ids-btn--link`. Currently they are set to use `--button-color-secondary-initial-font` but looks like they should be `--button-color-tertiary-initial-font`

**Comment by jmacaluso711** [comment]
🍌

**Pull request merged**
